/*
* generated by Xtext
*/
package com.br.terra.dcl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import com.br.terra.dcl.services.DCLGrammarAccess;

public class DCLParser extends AbstractContentAssistParser {
	
	@Inject
	private DCLGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected com.br.terra.dcl.ui.contentassist.antlr.internal.InternalDCLParser createParser() {
		com.br.terra.dcl.ui.contentassist.antlr.internal.InternalDCLParser result = new com.br.terra.dcl.ui.contentassist.antlr.internal.InternalDCLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getModDeclAccess().getAlternatives(), "rule__ModDecl__Alternatives");
					put(grammarAccess.getDCDeclAccess().getAlternatives(), "rule__DCDecl__Alternatives");
					put(grammarAccess.getElementTypeAccess().getAlternatives(), "rule__ElementType__Alternatives");
					put(grammarAccess.getBasicTypeAccess().getTypeNameAlternatives_0(), "rule__BasicType__TypeNameAlternatives_0");
					put(grammarAccess.getEntityTypeAccess().getEntityAlternatives_0(), "rule__EntityType__EntityAlternatives_0");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getModDeclAccess().getGroup_0(), "rule__ModDecl__Group_0__0");
					put(grammarAccess.getModDeclAccess().getGroup_1(), "rule__ModDecl__Group_1__0");
					put(grammarAccess.getModDeclAccess().getGroup_2(), "rule__ModDecl__Group_2__0");
					put(grammarAccess.getModDeclAccess().getGroup_3(), "rule__ModDecl__Group_3__0");
					put(grammarAccess.getModDeclAccess().getGroup_4(), "rule__ModDecl__Group_4__0");
					put(grammarAccess.getDCDeclAccess().getGroup_0(), "rule__DCDecl__Group_0__0");
					put(grammarAccess.getDCDeclAccess().getGroup_1(), "rule__DCDecl__Group_1__0");
					put(grammarAccess.getDCDeclAccess().getGroup_2(), "rule__DCDecl__Group_2__0");
					put(grammarAccess.getDCDeclAccess().getGroup_3(), "rule__DCDecl__Group_3__0");
					put(grammarAccess.getModelAccess().getModDeclAssignment_2(), "rule__Model__ModDeclAssignment_2");
					put(grammarAccess.getModelAccess().getDCDeclAssignment_6(), "rule__Model__DCDeclAssignment_6");
					put(grammarAccess.getModDeclAccess().getNameAssignment_0_1(), "rule__ModDecl__NameAssignment_0_1");
					put(grammarAccess.getModDeclAccess().getNameAssignment_1_1(), "rule__ModDecl__NameAssignment_1_1");
					put(grammarAccess.getModDeclAccess().getNameAssignment_2_1(), "rule__ModDecl__NameAssignment_2_1");
					put(grammarAccess.getModDeclAccess().getNameAssignment_3_1(), "rule__ModDecl__NameAssignment_3_1");
					put(grammarAccess.getModDeclAccess().getNameAssignment_4_1(), "rule__ModDecl__NameAssignment_4_1");
					put(grammarAccess.getDCDeclAccess().getTAssignment_0_1(), "rule__DCDecl__TAssignment_0_1");
					put(grammarAccess.getDCDeclAccess().getElementTypeAssignment_0_3(), "rule__DCDecl__ElementTypeAssignment_0_3");
					put(grammarAccess.getDCDeclAccess().getTypeAssignment_0_4(), "rule__DCDecl__TypeAssignment_0_4");
					put(grammarAccess.getDCDeclAccess().getTAssignment_1_0(), "rule__DCDecl__TAssignment_1_0");
					put(grammarAccess.getDCDeclAccess().getElementTypeAssignment_1_2(), "rule__DCDecl__ElementTypeAssignment_1_2");
					put(grammarAccess.getDCDeclAccess().getTypeAssignment_1_3(), "rule__DCDecl__TypeAssignment_1_3");
					put(grammarAccess.getDCDeclAccess().getTAssignment_2_0(), "rule__DCDecl__TAssignment_2_0");
					put(grammarAccess.getDCDeclAccess().getElementTypeAssignment_2_2(), "rule__DCDecl__ElementTypeAssignment_2_2");
					put(grammarAccess.getDCDeclAccess().getTypeAssignment_2_4(), "rule__DCDecl__TypeAssignment_2_4");
					put(grammarAccess.getDCDeclAccess().getTAssignment_3_0(), "rule__DCDecl__TAssignment_3_0");
					put(grammarAccess.getDCDeclAccess().getEntityTypeAssignment_3_2(), "rule__DCDecl__EntityTypeAssignment_3_2");
					put(grammarAccess.getDCDeclAccess().getTypeAssignment_3_3(), "rule__DCDecl__TypeAssignment_3_3");
					put(grammarAccess.getBasicTypeAccess().getTypeNameAssignment(), "rule__BasicType__TypeNameAssignment");
					put(grammarAccess.getEntityTypeAccess().getEntityAssignment(), "rule__EntityType__EntityAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			com.br.terra.dcl.ui.contentassist.antlr.internal.InternalDCLParser typedParser = (com.br.terra.dcl.ui.contentassist.antlr.internal.InternalDCLParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public DCLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DCLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
